Поправил скрипты развертывания, добавил startupProbe, добавил доки

diff --git a/app/templates/deployment.yaml b/app/templates/deployment.yaml
--- a/app/templates/deployment.yaml
+++ b/app/templates/deployment.yaml
@@ -13,16 +13,8 @@ spec:
     metadata:
       labels:
         app: app #метка для под
-      annotations:
-        vault.hashicorp.com/agent-inject: "true" # 1. Включаем инжектор Vault
-        vault.hashicorp.com/role: "app-role" # 2. Указываем созданную ранее роль
-        vault.hashicorp.com/agent-inject-secret-db-config: "minikube_secret/app-service" # 3. Указываем путь к секрету в Vault
-        vault.hashicorp.com/agent-inject-template-db-config: | # 4. ШАБЛОН: Как превратить данные из Vault в файл
-          {{ `{{- with secret "minikube_secret/app-service" - }}` }}
-          DATABASE_USERNAME="{{ `{{ .Data.data.username }}` }}"
-          DATABASE_PASSWORD="{{ `{{ .Data.data.password }}` }}"
-          {{ `{{ - end - }}` }}
     spec:
+      serviceAccountName: vault-auth
       imagePullSecrets:
         - name: gitlab-registry-key
       initContainers:
@@ -32,6 +24,25 @@ spec:
           args: #можно в конец еще добавить sleep 3600 для анализа содержимого init-sidecar контейнера
             - |
               apk add --no-cache curl jq
+
+              echo "--- Get VAULT_TOKEN ---"
+              JWT_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
+              RESPONSE=$(curl --request POST --data "{\"jwt\": \"$JWT_TOKEN\", \"role\": \"app-role\"}" $VAULT_ADDR/v1/auth/kubernetes/login)
+
+              if [ -z "$RESPONSE" ] || [ "$RESPONSE" == "null" ]; then
+                  echo "ERROR: Vault returned empty response"
+                 exit 1
+              fi
+
+              if echo "$RESPONSE" | jq -e '.errors' > /dev/null; then
+                  echo "ERROR: Vault returned API error:"
+                  echo "$RESPONSE" | jq '.errors'
+                  exit 1
+              fi
+
+              VAULT_TOKEN=$(echo "$RESPONSE" | jq -r '.auth.client_token')
+
+
               echo "--- Checking connection to Vault ---"
     
               RESPONSE=$(curl -s -H "X-Vault-Token: $VAULT_TOKEN" $VAULT_ADDR/v1/minikube_secret/data/app-service)
@@ -58,8 +69,6 @@ spec:
           env:
             - name: VAULT_ADDR
               value: "http://vault-server:8200"
-            - name: VAULT_TOKEN
-              value: "root"
           volumeMounts:
             - name: secret-storage
               mountPath: /vault/secrets
@@ -75,17 +84,23 @@ spec:
               name: app-config
         ports:
         - containerPort: 8082 #это порт которое слушает приложение фактически
+        startupProbe: 
+          httpGet:
+            path: /test_project/actuator/health/liveness
+            port: 8082
+          failureThreshold: 30
+          periodSeconds: 2
         readinessProbe: #анализирует готовность приложения отвечать на запросы
           httpGet:
             path: /test_project/actuator/health/readiness # должен содержать server.servlet.context-path
             port: 8082
-          initialDelaySeconds: 15 #первая проверка наступит через n секунд после старта контейнера
-          periodSeconds: 5 # делаем ретраи проверок каждые n секунд до первого успеха или failure раз (по умолчанию 3 раза, смотрим через kubectl describe pod)
+          initialDelaySeconds: 10 #первая проверка наступит через n секунд после старта контейнера
+          periodSeconds: 10 # делаем ретраи проверок каждые n секунд до первого успеха или failure раз (по умолчанию 3 раза, смотрим через kubectl describe pod)
         livenessProbe: #проверка залипания приложения, если не отвечает то перезагружаем
           httpGet:
             path: /test_project/actuator/health/liveness # должен содержать server.servlet.context-path
             port: 8082
-          initialDelaySeconds: 20 # по сути первая проверка после отработки readinessProbe время первого запуска тут readinessProbe.initialDelaySeconds + readinessProbe.periodSeconds
+          initialDelaySeconds: 15 # по сути первая проверка после отработки readinessProbe время первого запуска тут readinessProbe.initialDelaySeconds + readinessProbe.periodSeconds
         volumeMounts:
           - name: secret-storage
             mountPath: /vault/secrets
